server.port=8009

# \u8BBE\u7F6E\u54CD\u5E94\u7684\u5B57\u7B26\u7F16\u7801
server.servlet.encoding.charset=utf-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.application.name=SAA-09Text2image

# ====SpringAIAlibaba Config=============
spring.ai.dashscope.api-key=${aliQwen-api}
# \u589E\u52A0\u8FDE\u63A5\u8D85\u65F6\u548C\u8BFB\u53D6\u8D85\u65F6\uFF0C\u5355\u4F4D\u6BEB\u79D2\uFF08\u4F8B\u5982\u8BBE\u7F6E\u4E3A 60 \u79D2\uFF09
spring.ai.dashscope.read-timeout=60000